### ISSUE TITLE
Hangfire Dashboard History Graph shows incorrect data when using Hangfire.Mongo

### ISSUE THREAD

**Issue by mawl** [sergeyzwezdin/Hangfire.Mongo#121]
Hi,

After switching The history graph shows only 1 job a day, but we have about 300 succeeded jobs a week.

![image](https://user-images.githubusercontent.com/5493374/34039614-736f0738-e190-11e7-98d7-6ec9a17793fd.png)
![image](https://user-images.githubusercontent.com/5493374/34039625-82f0561c-e190-11e7-8fdd-4e6a6e545c6e.png)

Any ideas?

Regards
Marco

**Comment by MarLoe** [comment]
@mawl, sorry for the late reply.

Can you tell which versions of Hangfire and Hangfire.Mongo you are running?
What kind of jobs are you running (Enqueued, Scheduled, Recurring - or a mix)?

**Comment by mawl** [comment]
Hi @MarLoe,

It's 
```
<package id="Hangfire.Core" version="1.6.17" targetFramework="net462" />
<package id="Hangfire.Mongo" version="0.5.7" targetFramework="net462" />
```
We're only using Enqueued Jobs.

**Comment by MarLoe** [comment]
Despite a lot of detours, I am still looking into this issue. Hoping that a fix will make it in time for 0.5.8

**Comment by gottscj** [comment]
@mawl,

Just looked into this. It seems to be a bug in the dashboard. My weekly graph looks like this, but the Statistics object we return to Hangfire looks like this (in my test):
{"Servers":2,"Recurring":0,"Enqueued":1,"Queues":1,"Scheduled":0,"Processing":0,"Succeeded":1002,"Failed":0,"Deleted":0}
{"Servers":2,"Recurring":0,"Enqueued":1,"Queues":1,"Scheduled":0,"Processing":0,"Succeeded":1002,"Failed":0,"Deleted":0}
{"Servers":2,"Recurring":0,"Enqueued":0,"Queues":0,"Scheduled":0,"Processing":0,"Succeeded":1003,"Failed":0,"Deleted":0}
{"Servers":2,"Recurring":0,"Enqueued":0,"Queues":0,"Scheduled":0,"Processing":0,"Succeeded":1003,"Failed":0,"Deleted":0}
{"Servers":2,"Recurring":0,"Enqueued":0,"Queues":0,"Scheduled":0,"Processing":0,"Succeeded":1003,"Failed":0,"Deleted":0}

@odinserj is this something you recognize?
Thanks!

**Comment by gottscj** [comment]
I will clone hangfire and try to identify the bug...

**Comment by gottscj** [comment]
nope.. its our bug, its the AggregatedCounterDto collection which is the troublemaker. @MarLoe we should consider removing this and only use the CounterDto

**Comment by gottscj** [comment]
@mawl,

Should be fixed in #132

**Comment by mawl** [comment]
@gottscj,

Thanks for that.

I have tested it with 0.5.9, but the issue is still the same. I have created 5 Jobs. Daily history graph first says 4 jobs but after the 5th Job and around 5 minutes, it reduces it to one.

I use a mongodb/3.4.10-windowsservercore docker Image.

**Comment by gottscj** [comment]
@mawl,

hmm sounds like I need to look into this some more. sorry for the inconvience.

**Comment by gottscj** [comment]
@mawl,

A stupid mistake on my part. Addressed in #135

**Comment by mawl** [comment]
Hi @gottscj,

When will a new version be released that encloses the fix?

**Comment by gottscj** [comment]
@mawl,

We been very busy lately. Expect a new release the coming weekend. 

Thanks!

**Comment by gottscj** [comment]
@mawl,
We released 0.5.10 which contains fix for your issue. We are also upgrading to latest mongo C# driver and using the latest Hangfire.

Please let us know if it works as expected.

Thanks
